### ISSUE TITLE
什么时间开源模型代码以及发布预训模型参数？

### ISSUE THREAD

**Issue by xuehui0725** [brightmart/albert_zh#1]
请问下，模型代码以及发布预训模型参数会按照这个时间发布吗？
1、albert_base, 参数量12M, 层数12，10月5号

2、albert_large, 参数量18M, 层数24，10月13号

3、albert_xlarge, 参数量59M, 层数24，10月6号

4、albert_xxlarge, 参数量233M, 层数12，10月7号（效果最佳的模型

**Comment by brightmart** [comment]
是的，这个是发布计划

**Comment by brightmart** [comment]
主要的代码更新了

**Comment by brightmart** [comment]
released albert_base_zh & albert_large_zh, albert_xlarge and others will coming soon.
