### ISSUE TITLE
提供mxnet支持吗？

### ISSUE THREAD

**Issue by xf05888** [brightmart/albert_zh#10]
我想在[GluonNLP](https://www.github.com/dmlc/gluon-nlp) 中导入ALBERT，请问可否提供对mxnet的支持（例如param文件）？

**Comment by brightmart** [comment]
有TensorFlow checkpoint,怎么转maxnet,有这样的机制吗？pytorch里是有办法可以转的。

**Comment by w-zm** [comment]
> 有TensorFlow checkpoint,怎么转maxnet,有这样的机制吗？pytorch里是有办法可以转的。

您好，请问有转换为pytorch的转换脚本么？在pytorch-transformers也没有找到对应的代码，谢谢。

**Comment by brightmart** [comment]
有的，稍微改一改。

mv chinese_roberta/bert_config_middle.json chinese_roberta/config.json
python -u -m pytorch_transformers.convert_tf_checkpoint_to_pytorch --tf_checkpoint_path chinese_roberta/ --bert_config_file chinese_roberta/config.json --pytorch_dump_path chinese_roberta/pytorch_model.bin
bash run_roberta.sh
python combine.py --model_prefix ./model_roberta --out_path ./sub.csv

详见<a href='https://github.com/guoday/CCF-BDCI-Sentiment-Analysis-Baseline/blob/master/README.md'>guoday</a>

**Comment by w-zm** [comment]
> 有的，你需要稍微改一改。
> 
> mv chinese_roberta/bert_config_middle.json chinese_roberta/config.json
> python -u -m pytorch_transformers.convert_tf_checkpoint_to_pytorch --tf_checkpoint_path chinese_roberta/ --bert_config_file chinese_roberta/config.json --pytorch_dump_path chinese_roberta/pytorch_model.bin
> bash run_roberta.sh
> python combine.py --model_prefix ./model_roberta --out_path ./sub.csv
> 
> 详见[guoday](https://github.com/guoday/CCF-BDCI-Sentiment-Analysis-Baseline/blob/master/README.md)

好的谢谢。

**Comment by xf05888** [comment]
@brightmart 找到Tensorflow checkpoint转mxnet的脚本了[https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/conversion_tools/convert_tf_model.py](https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/conversion_tools/convert_tf_model.py)
这个可以用吗？

**Comment by brightmart** [comment]
可能不行，因为albert模型已经变了，不是bert的模型了。

mxnet可能不如tensorflow，pytorch使用的人更多，你可以直接使用这两者来做你的任务。非常简单的。下载预训练模型、克隆项目、训练模型

**Comment by xf05888** [comment]
@brightmart 好的，谢谢
