### ISSUE TITLE
关于参数共享特性的代码对应

### ISSUE THREAD

**Issue by 652994331** [brightmart/albert_zh#103]
您好，最近机器之心上有篇文章讲到，在小规模的albert上（tiny small 甚至是large） 如果我们不使用层间参数共享的特性，让他和原来的bert一样的话, 可能对于表现会有提升。想问问在代码中，具体体现参数共享特性　和　sop 任务这两部份，应该去看下代码中的哪一部分，感觉不是很清楚，望指明，谢谢

**Comment by brightmart** [comment]
共享特性:

**Comment by 652994331** [comment]
@brightmart  谢谢
