### ISSUE TITLE
Is it adaptive for "transformers" of huggingface?

### ISSUE THREAD

**Issue by ShaneTian** [brightmart/albert_zh#104]
**Is it adaptive for [huggingface transformers](https://huggingface.co/transformers/index.html)?**
1. If it is, should I use which "[shortcut name](https://huggingface.co/transformers/pretrained_models.html)"?
2. If not, Is there an adaptation plan?

Thanks!

**Comment by brightmart** [comment]
it is not adaptive for huggingface transformers.
there is no shortcut name yet. you can have a try.

**Comment by ShaneTian** [comment]
> it is not adaptive for huggingface transformers.
> there is no shortcut name yet. you can have a try, or you can pytorch version we provide, just search pytorch in readme.

OK. Thank you~

**Comment by brightmart** [comment]
![image](https://user-images.githubusercontent.com/19634224/76162201-34514d00-6176-11ea-9d23-e94fc4f6529b.png)

**Comment by ShaneTian** [comment]
@brightmart Thank you! I got it!
