### ISSUE TITLE
English pre-trained release?

### ISSUE THREAD

**Issue by jpcorb20** [brightmart/albert_zh#11]
Hello,

Are you planning on releasing English pre-trained versions of Albert in the future?

Thank you,

**Comment by brightmart** [comment]
as albert albert already achieved state of the art performance of main english benchmarks, i think authors of the paper will release english revision in the near future.

**Comment by jpcorb20** [comment]
Yes, it is true. I haven't found any info on a release yet. Maybe, I should train one myself. Thank you very much.

**Comment by brightmart** [comment]
thank you. where can i find english corpus that used in the papers?

**Comment by jpcorb20** [comment]
If I am not mistaken, it is the same as [BERT](https://github.com/google-research/bert#pre-training-data). It is [BookCorpus](https://yknzhu.wixsite.com/mbweb) and [English Wikipedia](https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2) (the pre-processing here https://github.com/attardi/wikiextractor).

Awesome work by the way to reproduce ALBERT.

**Comment by brightmart** [comment]
great. thanks.

**Comment by pohanchi** [comment]
Hi , I am also interested in this idea, by the way do u have bookcorpus data?

**Comment by brightmart** [comment]
were you able to find bookcorpus using jpcorb20's link above?

**Comment by pohanchi** [comment]
No, but I ‘m curious about that. Bc I try to find it. But I didn’t get sth link

**Comment by jpcorb20** [comment]
You are right, sorry, the link inside is down. At the moment, the only thing I found is this library to crawl the original website: https://github.com/soskek/bookcorpus ...

**Comment by pohanchi** [comment]
ok, thanks. I just want that dataset  XD
