### ISSUE TITLE
请问发布的时候如何删除部分参数呢？

### ISSUE THREAD

**Issue by loserdog-err** [brightmart/albert_zh#117]
感谢作者的开源！
请问在您的模型上进一步 pretrain 之后，如何做到发布的时候只保存跟您模型(例如 tiny)一样的参数呢？代码中哪里可以设置呢？ 谢谢。

**Comment by brightmart** [comment]
启动一个预测，然后用类似这样的代码去保存：

    trainable_variable_list=tf.trainable_variables()
    trainable_variable_list=[x for x in trainable_variable_list if 'adam' not in x.name]
    saver_new=tf.train.Saver(trainable_variable_list)
    saver_new.save(sess,BERT_BASE_DIR_NEW)

**Comment by loserdog-err** [comment]
> 启动一个预测，然后用类似这样的代码去保存：
> 
> ```
> trainable_variable_list=tf.trainable_variables()
> trainable_variable_list=[x for x in trainable_variable_list if 'adam' not in x.name]
> saver_new=tf.train.Saver(trainable_variable_list)
> saver_new.save(sess,BERT_BASE_DIR_NEW)   
> ```

好的，谢谢
