### ISSUE TITLE
train.txt文件链接失效~

### ISSUE THREAD

**Issue by duanxingjian** [brightmart/albert_zh#118]
https://github.com/brightmart/albert_zh/blob/c18bea90c1cc4bd5640826fe693d2c335b9bfb31/run_classifier_lcqmc.sh#L30

新手上路，测试https://github.com/brightmart/albert_zh/blob/master/run_classifier_lcqmc.sh
发现无法下载以下三个文件，可否考虑重新上传？
wget -c https://raw.githubusercontent.com/pengming617/text_matching/master/data/train.txt
wget -c https://raw.githubusercontent.com/pengming617/text_matching/master/data/dev.txt
wget -c https://raw.githubusercontent.com/pengming617/text_matching/master/data/test.txt

**Comment by NextGuido** [comment]
@duanxingjian https://drive.google.com/file/d/1HXYMqsXjmA5uIfu_SFqP7r_vZZG-m_H0/view，试试这个
