### ISSUE TITLE
请问一下SOP模块在哪，怎么还是“run_pretraining.py”里还是NSP呢？

### ISSUE THREAD

**Issue by rogerrojur** [brightmart/albert_zh#12]

**Comment by brightmart** [comment]
SOP模块，生成的内容方式已经改了，名称没有沿用之前的。
具体内容见：create_instances_from_document_albert at <a href="https://github.com/brightmart/albert_zh/blob/master/create_pretraining_data.py">create_pretraining_data</>

**Comment by rogerrojur** [comment]
找到了，注释很详细，非常有用
