### ISSUE TITLE
Can the albert_zh  run squad?

### ISSUE THREAD

**Issue by elliotthwang** [brightmart/albert_zh#120]
Can the albert_zh  run squad?

**Comment by brightmart** [comment]
yes it can run chinese version of squad.

**Comment by brightmart** [comment]
check here by using its baseline: https://github.com/CLUEbenchmark/CLUE

**Comment by elliotthwang** [comment]
@brightmart  Thanks!

However, failed to adopted "30k-clean.model" as spm_model_file
Should back to old fashion to vocab.txt

**Comment by brightmart** [comment]
yeah

**Comment by elliotthwang** [comment]
Thank a lot!
