### ISSUE TITLE
加载使用albert base正常，加载albert tiny or small报错

### ISSUE THREAD

**Issue by sataliulan** [brightmart/albert_zh#132]
ValueError: Asked to get output at node 11, but the layer has only 4 inbound nodes.
如上所示，我利用bert4keras加载albert base是正常的，换成albert的其他版本就不行了，不知道哪位大佬遇到过么？

**Comment by Geekzhangwei** [comment]
那是因为你的bert_layers设置的不是4，改为4就可以了。
