### ISSUE TITLE
加载albert_base和albert_large准确率正常，80%多，但加载albert_xlarge准确率约等于零，请问大神们这是怎么回事，同一数据集

### ISSUE THREAD

**Issue by ann22** [brightmart/albert_zh#138]

**Comment by brightmart** [comment]
albert_xlarge模型比较大， 稳定性有点问题。这可能是你的数据集太小，

**Comment by afterQingming** [comment]
有可能是xlarge本身的BUG。官方论文中head num 应该是hidden size/64，即在xlarge中head num应为32，而我看很多地方都是16,（google的据说模型参数文件中是32，但是配置上写的16）
