### ISSUE TITLE
albert使用的时候,显存减少了吗?训练速度加快了吗?

### ISSUE THREAD

**Issue by swy0915** [brightmart/albert_zh#15]
albert使用的时候,显存减少了吗?训练速度加快了吗?

我现在最直观的是觉得模型文件大小比bert小了很多,但是好像使用的时候显存和bert差不多.但是我看有些文章里写的是 1 解决了内存限制问题 2 训练速度加快. 我怎么没感觉到啊. 谁能帮忙解释下？

**Comment by natureLanguageQing** [comment]
显存没减少 ，小albert快了一点，大的还没试过。看readme大albert还是很消耗显存的

**Comment by brightmart** [comment]
![896F1691802204D92233057849320EEE](https://user-images.githubusercontent.com/19634224/66409540-55750c80-ea23-11e9-97be-2be9dcb789b7.jpg)

"今天测试了下速度和显存。发现ALBERT差不多比Roberta快20%，节约20%显存吧".
