### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by xiaoxiao111111** [brightmart/albert_zh#164]
![image](https://user-images.githubusercontent.com/62454584/140738554-cb2e355e-e5db-421a-9296-df6fa041a030.png)
您好，请问模型训练后出现空白的标签是什么原因？

**Comment by brightmart** [comment]
哪里空白呢？是不是就是为0的地方啊，也就是没有实体信息。

**Comment by xiaoxiao111111** [comment]
> 哪里空白呢？是不是就是为0的地方啊，也就是没有实体信息。

是的，就是这个没有实体信息的地方，我只标注了TCMsyndrome,disease,inspect,symptome,treatment五个标签，但训练之后除了识别这五类实体，就还有个空白的，也就是为0的地方，这是为什么会识别出这个？这个会不会对模型的性能有影响？谢谢您的回复哦！
