### ISSUE TITLE
使用albert_large运行报错，感觉是word embedding的dim不对，求帮助

### ISSUE THREAD

**Issue by OYE93** [brightmart/albert_zh#17]
ValueError: Shape of variable bert/embeddings/word_embeddings:0 ((21128, 1024)) doesn't match with shape of tensor bert/embeddings/word_embeddings ([21128, 128]) from checkpoint reader.
报错如上
我是直接跑了bert官方的分类脚本，用bert的时候没有问题，不知道是不是embedding的dim设置不一样，作者你在跑分类的时候有修改其他 代码吗？感谢

**Comment by brightmart** [comment]
你好，跑albert的模型需要用albert的代码，不能用bert,因为模型变了

**Comment by OYE93** [comment]
感谢回复，我在fine-tuning的时候是需要用你这个repo里的run_classification.py吗？能大概了解一下，是哪些地方有修改吗，谢谢

**Comment by brightmart** [comment]
你需要用这个项目，包括模型文件。就是直接clone项目再按照示例跑一跑，改一改方面。

**Comment by OYE93** [comment]
好吧，谢谢了

**Comment by xxllp** [comment]
可惜了  原以为还能公用的呢
