### ISSUE TITLE
基于albert_xlarge_zh fine_tune跑分类任务，收敛速度比bert_base慢？

### ISSUE THREAD

**Issue by nonva** [brightmart/albert_zh#18]
设置同样的batch_size, max_seq_len,  learning_rate，epoch_num;  分类任务跑同样的40w数据量bert_base 12小时可以跑完， 而albert_xlarge_zh目前跑了24小时好像1个epoch都没跑完，请问这个正常么？ 还是执行哪些地方配置修改有问题？

**Comment by brightmart** [comment]
xlarge是比large还大一号，所以你可能可以预期慢4倍。目前albert_xlarge_zh这几天还要推出新的版本，现在可以先尝试albert_base和albert_large.

**Comment by nonva** [comment]
> xlarge是比large还大一号，所以你可能可以预期慢4倍。目前albert_xlarge_zh这几天还要推出新的版本，现在可以先尝试albert_base和albert_large.

了解，“xlarge是比large还大一号“指什么方面大？ 我看介绍提到xlarge 参数量和模型大小为bert_base的二分之一,   为什么训练速度更慢呢？

**Comment by brightmart** [comment]
你好，“xlarge是比large还大一号”，是指参数量、模型文件大小、hidden_size的大小。
albert是通过参数共享等方式将参数量减少了，但那些层还都在，而且xlarge的hidden_size比bert_base要大很多，相当于比bert_large还大一号。

**Comment by JQIANG125** [comment]
> 你好，“xlarge是比large还大一号”，是指参数量、模型文件大小、hidden_size的大小。
> albert是通过参数共享等方式将参数量减少了，但那些层还都在，而且xlarge的hidden_size比bert_base要大很多，相当于比bert_large还大一号。

所以说论文中标榜albert比bert速度快是不是在不同的batch size下比较的？
