### ISSUE TITLE
虽然参数减少，但是inference的速度并没有减少太多，只是提高的训练速度？

### ISSUE THREAD

**Issue by RyanHuangNLP** [brightmart/albert_zh#2]
by the way，预训练的代码会release吗？

**Comment by xuehui0725** [comment]
同问，inference的速度是否比bert快？

**Comment by brightmart** [comment]
代码可以的；速度有机会更快，它有好几个大小的版本

**Comment by RyanHuangNLP** [comment]
我看论文里面，感觉inference速度提升就是在embedding分解那里，然后12层layer共享同一个Transformer block 的参数，所以觉得总的参数并没有减少太多，只是训练的参数减少。期待大佬的预训练模型

**Comment by brightmart** [comment]
参数通过词嵌入层变换和参数共享，是显著减少了。

**Comment by brightmart** [comment]
哎呀，inference从结论看，不是提升了，很可能是下降了，训练速度也下降了。

**Comment by cavities** [comment]
主要存储小很多 也就是说 ensemble 更加适合

**Comment by RyanHuangNLP** [comment]
我之前尝试过，在nmt中，transformer的ffn不用fc，改用conv1d共享，参数会减少一点

**Comment by brightmart** [comment]
是的。
<a href="https://github.com/brightmart/albert_zh/issues/7">关于超参数intermediate_size</a>,有人了解吗

**Comment by RyanHuangNLP** [comment]
FFN中的中第一层的升维度，在attention is all you need 中有提及
![image](https://user-images.githubusercontent.com/49582480/65830240-36b69d80-e2e0-11e9-81ee-0427a1a3aaa6.png)

**Comment by brightmart** [comment]
是的

**Comment by rogerrojur** [comment]
请问既然12层的transformer都是共享参数的，那么取多层输出还有意义吗，感觉取最后一层就好了，取多层数值有区别，但是总感觉信息量都是一致的

**Comment by brightmart** [comment]
感觉主要取最后一层就可以了。 @rogerrojur

**Comment by brightmart** [comment]
参数能减少多少呢？能否具体化解释一下，还有效果上有什么变化 @RyanHuangNLP

**Comment by QianchaoLiu** [comment]
> 我看论文里面，感觉inference速度提升就是在embedding分解那里，然后12层layer共享同一个Transformer block 的参数，所以觉得总的参数并没有减少太多，只是训练的参数减少。期待大佬的预训练模型

embedding分解多了一层映射，虽然减少了参数但inference的时候应该更耗时

**Comment by zhengwsh** [comment]
同样的代码，把预训练模型bert换成albert后，finetune速度明显变慢了，能解释下原因么

**Comment by nonva** [comment]
> 训练速度也下降了

训练速度也比原生bert下降？

**Comment by Cumberbatch08** [comment]
@brightmart  您好，我下载了代码，还没有完成训练；想问一下您：这个在线推理时间是明确比bert快吗？怎么大家都还不确定呢？

**Comment by brightmart** [comment]
tiny版本，明确的比bert快了很多，具体你可以看看README的效果对比

**Comment by Chandler-Bing** [comment]
@brightmart  作者您好，tiny版本在gpu上的单条速度大概是cpu上的1.3倍，这个提速是不是有点慢？是gpu利用率的问题吗？

**Comment by brightmart** [comment]
gpu感觉是batch化才有好的效率提升吧
