### ISSUE TITLE
SOP data preparation

### ISSUE THREAD

**Issue by wxiaopei** [brightmart/albert_zh#23]
Hi, 
When generating SOP train instances, if there is only one sentence in the document. Or other extreme case: every sentences in the doc are very long (i.e. more than the `target_token_num`), 
The generated output is
`[CLS] tokens_a [SEP] tokens_a[SEP].`  This is due to the `continue` statement without increasing index `i` in `create_instances_from_document_albert()`. 

If there is only one sentence in the current chunk, in order to do SOP, how about we randomly find a split position in the `tokens_a`? all tokens after that position will go to `tokens_b`. Tokens before that position will assign to `tokens_a`. 
```                  
 if len(tokens_b) == 0 and len(current_chunk) == 1:
                        if len(tokens_a) > 1:
                            #There is only one sentence in the chunk. The sentence could be very long. Or it is the last one in the document.
                            #In order to make SOP, we need to split the sentence into 2 parts.
                            index = rng.randint(1, len(tokens_a) - 1)
                            # index = int(len(tokens_a)/2)
                            tokens_b = tokens_a[index:]
                            tokens_a = tokens_a[0:index]
                        else:
                            print("only 1 token in tokens_a, can't split it into 2 parts. just skip this sentence.")
                            break
```

**Comment by brightmart** [comment]
Hi. there are multiple sentences in a document. since corpus comes like Wikipedia or news, general speaking there are long sequences, longer than max sequence length. however there are also some times short than max sequence length.
