### ISSUE TITLE
albert模型预测速度远小于bert

### ISSUE THREAD

**Issue by chros425** [brightmart/albert_zh#25]
您好，请问下我用Albert模型精调的分类模型，主要参数如下，使用了GitHub上放出来的两个xlarge模型 albert_xlarge_zh_177k和albert_xlarge_zh_183k
  --do_train=true \
  --do_eval=true \
  --do_predict=false \
  --do_export=false \
  --vocab_file=$BERT_BASE_DIR/vocab.txt  \
  --bert_config_file=$BERT_BASE_DIR/albert_config_xlarge.json \
  --init_checkpoint=$BERT_BASE_DIR/albert_model.ckpt \
  --max_seq_length=32 \
  --train_batch_size=64 \
  --save_checkpoints_steps=500 \
  --max_steps_without_decrease=15000 \
  --learning_rate=1e-6 \
  --num_train_epochs=10 \

python：3.6.4
TensorFlow：1.14
训练：GPU V100
预测：戴尔笔记本
使用 tornado做web框架，都在我自己本地笔记本电脑上测试，测试代码完全一样
bert 预测耗时220ms，
Albert 预测耗时2200ms
这个差距有点大，不是说模型更小，参数更少，预测的速度不会更快是吗，请大佬赐教。

**Comment by brightmart** [comment]
哦，xlarge比bert base大两号，慢一点是正常的，但这个在你这里的差距有点大哦。 其他服务器上的效果如何？ 如果要更快的，试一试新推出的albert_tiny:预测速度提升10倍；在比较简单的任务场景，精度基本保留，不使用特别复杂的任务，

**Comment by Jasperty** [comment]
i get 250ms for bert(base) and get 1500ms for al-bert(tiny)

**Comment by sygspjlsj** [comment]
我理解的有可能跟作者调用的方式有关，作者使用了Estimator，而Estimator每次调用train，evaluate ，predict的时候都会从检查点重新load模型，初始化权重值，这就导致了时间的增加。
