### ISSUE TITLE
Are you going to publish pre-trained English Models as well?

### ISSUE THREAD

**Issue by dilaratorunoglu** [brightmart/albert_zh#27]
Hello,

I have e-mailed you about this issue. I would be happy if you answer my question.
Are you going to publish pre-trained English models as well? 

Thank you so much.
D

**Comment by brightmart** [comment]
Hi D,

Just saw your email. 

I will able to reply to you yes or not on Tomorrow night. and if you need english model, do you need a base, large or xlarge of albert?

B

**Comment by brightmart** [comment]
Hi D, 

The authors of albert paper is going to release english version these days, very soon, with a really good english model, it will be state of the art.  Let's just wait for a while.

brightmart

**Comment by dilaratorunoglu** [comment]
Thank you so much.

D.

**Comment by arvindpdmn** [comment]
Have the English models been released? Please share the link. Thanks
