### ISSUE TITLE
create_pretraining_data.py   line 322

### ISSUE THREAD

**Issue by kyang888** [brightmart/albert_zh#28]
Hello,brightmart:
        Thank you  for  Implementation of albert. When I see ine 322 of  create_pretraining_data.py 
              `if len(tokens_a)==0 or len(tokens_b)==0: continue`
       I have a problem: 
               if  list  current_chunk  only have the  last sentence of document, current_chunk will have 
               two  same sentences. Then tokens_a is  last sentence and  tokens_b is also last sentence.

**Comment by ywl0911** [comment]
I'm alse confused about this issue. To modify the code as follow may be OK？
> if len(tokens_a) == 0 or len(tokens_b) == 0: break

or

> if len(tokens_a) == 0 or len(tokens_b) == 0:  i+=1; continue

**Comment by brightmart** [comment]
确实有这个问题，已经更新了，非常感谢。
