### ISSUE TITLE
缺少基于用户输入的预测

### ISSUE THREAD

**Issue by stopit** [brightmart/albert_zh#35]
现有的用例展示的是对于文本的批量运算，缺少基于用户输入的预测。使用他开源bert工具（基于tf）调用tiny_bert模型进行用户输入预测时总是报：部分变量与checkpoint中的shape不同的错误，无法正常运行。

**Comment by brightmart** [comment]
具体错误能否贴出来呢？“他开源bert工具”是指什么？

**Comment by stopit** [comment]
谷歌代码里：https://github.com/google-research/bert/blob/master/modeling.py   line：177 中：
`embedding_size=config.hidden_size,`

本项目内
```
hidden_size=config.hidden_size,
embedding_size=config.embedding_size,
```

导致利用谷歌原始的程序加载本项目训练得到的模型时，会造成：
程序中embedding相关变量的shape  与  模型文件中的shape不一致，无法通过tf的校验，直接退出。

**Comment by brightmart** [comment]
你需要使用albert_zh的代码，特别是这个项目的modelling的代码。
