### ISSUE TITLE
预训练模型无法下载

### ISSUE THREAD

**Issue by qtzheng** [brightmart/albert_zh#38]
https://storage.googleapis.com/albert_zh/albert_base_zh_additional_36k_steps.zip

这些链接都无法下载了

**Comment by brightmart** [comment]
哦，看到了，误操作导致的。你可以加群，向群友要一下。这个晚上就会恢复了。

**Comment by Peterisfar** [comment]
请问恢复了吗

**Comment by brightmart** [comment]
已经恢复了，请尝试
