### ISSUE TITLE
请问embedding层的因式分解具体实现方式是怎么样的？

### ISSUE THREAD

**Issue by ewrfcas** [brightmart/albert_zh#4]
从论文中我猜测是embedding到128维后接一个全连接到高维？
还是说有其他的实现方式，论文中感觉没有讲得很清楚

**Comment by brightmart** [comment]
感觉已经讲清楚了，就是变换一下。

**Comment by fengzuo97** [comment]
论文这一块有点简略，因式分解应该是指，除了embedding层的V * E的参数之外，还有一个E * H的参数矩阵，数据通过embedding后，维度变为E，再乘以参数矩阵，维度变为H，然后embedding层的参数就是V * E + E * H，但是这个感觉和数学上的因式分解不一样。

**Comment by brightmart** [comment]
you can check the codes under test_changes.py
