### ISSUE TITLE
final layer normalization

### ISSUE THREAD

**Issue by zxgineng** [brightmart/albert_zh#41]
> The Pre-LN Transformer
puts the layer normalization inside the residual
connection and equips with an additional finallayer normalization before prediction 

在prelln_transformer_model中我没找到这个final layer normalization 
请问是我遗漏了还是您没有实现这层呢

**Comment by brightmart** [comment]
试了， 没有效果有问题，后来就去掉了。你在 modelling.py可以搜到pre ln 相关的内容
