### ISSUE TITLE
关于xlarge模型的batch_size和学习率

### ISSUE THREAD

**Issue by DunZhang** [brightmart/albert_zh#56]
您好，我最近在使用xlarge-albert在自己任务上微调，起初我设置的batch_size是16，学习率是2e-5，然后训练过程中发现loss震荡的厉害，验证集效果极差。
然后，我把学习率调低到2e-6，发现效果好一些，但是验证集精度仍然和原始bert有差距。
最后，我又继续把学习率调低到2e-7，发现效果又会好一些，但是和原始bert还是有差距。另**外和使用albert-base相比也有差距**，所以我觉得是训练出了问题。
所有我想请教下您，使用xlarge-albert微调时，学习率和batch_size需要设置成多少合适呢？我看到您说batch_size不能太小，否则可能影响精度，我16的batch_size是否过小了？

**Comment by 652994331** [comment]
我感觉太小了， 我提了同样的问题。 我自己的数据在base 的基础上pretrain 再 finetune 一个分类任务，得到的准确率86%多。 按这样的结果看 xlarge 至少要 128 才比较好。 但是OOM 的问题解决不了

**Comment by DunZhang** [comment]
对的，现在已经不打算使用albert了，除了预测时占的内存(显存少)，训练时的显存占用和时间花销并没有节省
