### ISSUE TITLE
模型训练的设备要求是什么

### ISSUE THREAD

**Issue by cedar33** [brightmart/albert_zh#6]
模型训练需要多大显存，训练时长大概是多久

**Comment by brightmart** [comment]
如果是调优finetuning的话，和bert类似级别，参数少了一些。


System | Seq Length | Max Batch Size
-- | -- | --
BERT-Base | 64 | 64
... | 128 | 32
... | 256 | 16
... | 320 | 14
... | 384 | 12
... | 512 | 6
BERT-Large | 64 | 12
... | 128 | 6
... | 256 | 2
... | 320 | 1
... | 384 | 0
... | 512 | 0

**Comment by cedar33** [comment]
> 如果是调优finetuning的话，和bert类似级别，参数少了一些。
> 
> System	Seq Length	Max Batch Size
> BERT-Base	64	64
> ...	128	32
> ...	256	16
> ...	320	14
> ...	384	12
> ...	512	6
> BERT-Large	64	12
> ...	128	6
> ...	256	2
> ...	320	1
> ...	384	0
> ...	512	0

好的，谢谢，还是练不起 :-)

**Comment by brightmart** [comment]
也会有小号版本，可以使用
