### ISSUE TITLE
想请教为何您的albert和roberta预训练速度都很慢?

### ISSUE THREAD

**Issue by ahzz1207** [brightmart/albert_zh#62]
您好,首先感谢您开源的这些代码.
我最近在尝试重头训练不同版本的bert并在Chinese-GLUE上验证,
1) 我使用您的albert创造预训练数据的代码,构造的预训练数据相比google官方的大小约是0.6倍(参数相同)
2)请问为何在bash文件中您将复制数设为5,最大mask设为23呢?
3)我使用您写的albert和roberta的预训练代码, 在8块1080ti上,只能接受32的batchsize(128长度),而使用官方原版的bert代码可以使用128的batchsize,这是为何呢?在阅读pretraining的代码后并没有发现有何不同...

**Comment by brightmart** [comment]
1. google官方的代码，使用的是span mask，复制数比较多
2.复制数可以设大一点，如果要效果更好一些；mask大小不要太大，否则可能比较难学
3.使用显存的问题，主要由模型决定的，和预训练的代码应该关系不大。

**Comment by ahzz1207** [comment]
> 1. google官方的代码，使用的是span mask，复制数比较多
>    2.复制数可以设大一点，如果要效果更好一些；mask大小不要太大，否则可能比较难学
>    3.使用显存的问题，主要由模型决定的，和预训练的代码应该关系不大。

谢谢回复,训练速度发现是我自己的问题.
