### ISSUE TITLE
关于下游任务的问题

### ISSUE THREAD

**Issue by 652994331** [brightmart/albert_zh#65]
我们用自己的数据在现有的albert 基础上，又对他进行了预训练，　之后　我们得到了我们的预训练模型，现在想在下游任务上看一下他的表现，　想问一下现在Ａｌｂｅｒｔ的下游finetune (run_classifier) 和　普通的有所不同吗，是否可以在下游接上普通的run_classifier(原始bert 的)任务？　谢谢

**Comment by brightmart** [comment]
可以的。见项目中下游任务例子
