### ISSUE TITLE
关于超参数intermediate_size

### ISSUE THREAD

**Issue by beamind** [brightmart/albert_zh#7]
代码中设置的intermediate_size=4096。按我的理解，论文(第4页第2行)里说intermediate_size是4倍的hidden size，应该是16384。不知道是不是我理解错了。感谢解答！

**Comment by brightmart** [comment]
这好像太大了，你再确认一下，其他同学有了解的吗？bert里large的原先也才4096，

**Comment by brightmart** [comment]
确实是intermediate_size是4倍的hidden size，所以xxlarge的intermediate_size是16384

**Comment by YC-wind** [comment]
去掉这个 超参数 会怎么样？或者 使用 cnn/rnn等 替代 dense；原始attention layer 之后接 768*768 + 768*3072 + 3072*768（dropout/LN没写在内）；这个参数量占比最多，会不会影响性能呢

**Comment by pohanchi** [comment]
太感謝了 收益良多

**Comment by brightmart** [comment]
thanks
