### ISSUE TITLE
albert？模型文件怎么和谷歌的差那么多？

### ISSUE THREAD

**Issue by hefeiyun** [brightmart/albert_zh#72]
为啥modeling.py里面写的是class BertModel(object)？
谷歌https://github.com/google-research/google-research/blob/master/albert/modeling.py 里面写的可是class AlbertModel(object) 。

**Comment by hefeiyun** [comment]
abondon

**Comment by brightmart** [comment]
使用方式见【下游任务】的例子。

我的版本是用自动用modeling.py，google的版本会用项目里的：modeling_google.py
![image](https://user-images.githubusercontent.com/19634224/69332798-6192f180-0c92-11ea-92dd-a56135f06089.png)
