### ISSUE TITLE
running create_pretraining_data.py shows "Wrote 0 total instances".

### ISSUE THREAD

**Issue by Muntasir13** [brightmart/albert_zh#75]
I am trying to pretrain a model using multilingual BERT model. Vocab.txt was changed in ./albert_config. After running create_pretraining_data.py, it is showing "Wrote 0 total instances". Is this what it was supposed to show?

**Comment by BruceLoveDecimal** [comment]
I have met this problem too. How did u solve this problem, Muntasir?

**Comment by Muntasir13** [comment]
This was a long time ago. As far as I can remember, I was not able to solve this problem. I had to go for other models
