### ISSUE TITLE
train albert on my own data, convergence speed is slow

### ISSUE THREAD

**Issue by yyht** [brightmart/albert_zh#8]
hi, i tried to train albert on my own data using 32-gtx1080Ti, i found that after some steps, loss could not decrease and it seems stuck on local minimal.
![image](https://user-images.githubusercontent.com/14133687/65829027-b12cf080-e2d3-11e9-9c99-c9985fcdcb33.png)

**Comment by brightmart** [comment]
can you paste your configuration here to have a look?
你可以把你的相关的训练相关的参数配置信息贴出来，看看吗。如训练什么型号的、参数配置、batch_size，数据量什么的。

**Comment by yyht** [comment]
albert-12, embedding_size=128, hidden_size=768, intermediate_size=1024, number_of_layers=12
batch_size=24(32张卡，相当于 batch_size=768).

**Comment by brightmart** [comment]
好的。看到了。
1、intermediate_size应该是4*hidden_size，
2、之前的run_pretraining.py里没有把段落连续性的损失加到总loss里。

你可以先改一下，再试一试；如果loss还很大的话，稍等一两天，还会有更新。

**Comment by yyht** [comment]
我觉得 和 intermediate_size 的size 大小 应该 相关度不高，稍微小一些  应该 也能 收敛，现在 看 曲线 感觉 mlm loss stuck 在 局部 极致点附近了，下降很慢（或者 进入 饱和区 之类的）
另外，40G 的文本 可以 分享一下嘛

**Comment by yyht** [comment]
我知道原因了，主要是 embedding matrix、projection matrix 需要 连续的矩阵乘法，这样，会导致 他们的 元素 比 之前小很多，对 projection 后的tensor 乘以2 可以 保持 值域类似，收敛效果会好很多
![image](https://user-images.githubusercontent.com/14133687/65832706-0e3b9d00-e2fa-11e9-9d5f-257ebbdca586.png)

**Comment by brightmart** [comment]
怎么理解，有根据吗。有没有更好的解释

**Comment by yyht** [comment]
我离线做 embedding 和projection矩阵直接matmul，得到的值域 比 单纯 embedfing要小一倍左右，过小的参数范围 导致 优化 容易 在 0附近徘徊？明天 手动推导一下，乘以2后 收敛效果好了很多（图里面是 三层的结果）发自我的华为手机-------- 原始邮件 --------发件人： brightmart <notifications@github.com>日期： 2019年9月29日周日 21:07收件人： brightmart/albert_zh <albert_zh@noreply.github.com>抄送： yyht <htxu91@gmail.com>, State change <state_change@noreply.github.com>主    题： Re: [brightmart/albert_zh] train albert on my own data, convergence speed is slow (#8)怎么理解，有根据吗。有没有更好的解释

**Comment by wsn555** [comment]
想请问一下 上面那个收敛到3的曲线是3层layer吗

**Comment by wsn555** [comment]
我在训练的时候发现，12层的albert-xxlarge模型loss无法很好的下降，但是将隐层缩减为3层之后，反而能下降的很迅速。楼主如果也是3层的话，那上图loss能下降的原因可能不是因为乘了2，而是减少了layer

**Comment by lonePatient** [comment]
看样子应该是数据量比较小吧，如果用12层的话，学习率是调整的。
