### ISSUE TITLE
module 'tensorflow_core._api.v2.train' has no attribute 'Optimizer'

### ISSUE THREAD

**Issue by ntedgi** [brightmart/albert_zh#80]
when running `run_classifier_lcqmc.sh`
 
Start running...
Traceback (most recent call last):
  File "run_classifier.py", line 25, in <module>
    import optimization_finetuning as optimization
  File "/Users/naortedgi/Desktop/albert/albert_zh/optimization_finetuning.py", line 87, in <module>
    class AdamWeightDecayOptimizer(tf.train.Optimizer):
AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'Optimizer'

**Comment by brightmart** [comment]
use tensorflow 1.x , e.g. 1.4 or 1.5

**Comment by ntedgi** [comment]
thanks @brightmart !
maybe let's add a requirement file to avoid other getting this issue

**Comment by brightmart** [comment]
yes, that's do that.
