### ISSUE TITLE
albert_base couldn't find checkpoint

### ISSUE THREAD

**Issue by Zessay** [brightmart/albert_zh#88]
albert_base_zh(额外训练了1.5亿个实例即 36k steps * batch_size 4096) 转换成pytorch.bin的过程中会发生 "couldn't find checkpoint"的错误，其他模型都没有问题。

**Comment by GanjinZero** [comment]
出现了同样的问题

**Comment by Zessay** [comment]
> 出现了同样的问题

已经解决了，将文件夹下的checkpoint文件里面的内容修改为：
```
model_checkpoint_path: "albert_model.ckpt"
all_model_checkpoint_paths: "albert_model.ckpt"
```

就可以了！
