### ISSUE TITLE
您好，请教一下fine tuning问题

### ISSUE THREAD

**Issue by lisuq** [brightmart/albert_zh#96]
我在多标签分类问题上对比了一下谷歌官方的bert_base_zh和您的albert_base_zh，虽然albert的Trainable params数量减少了，但是微调速度并没有加快，得分差不多，小幅度提高batchsize也还是会报OOM错误。请问一下，albert相对bert的优势在哪？在微调阶段两者是否没有差别？

**Comment by brightmart** [comment]
优势就是体积更小了、可以使用更大版本的模型了。

**Comment by lisuq** [comment]
> 优势就是体积更小了、可以使用更大版本的模型了。

感谢您的回答！
理论上albert_base_zh比bert_base小很多，为什么batchsize由6改为8这样小幅度提升仍然会报OOM错误？而且可训练参数减少那么多，训练速度仍没有加快。请问一下要跑起来albert large一般显存需要多大？
